name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] # windows-latest not working with 1.18 atm
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: "1.18"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
